name: Scheduled Health Check

permissions:
  contents: write

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo (self)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Clone private repo for config
        env:
          PRIVATE_REPO_PAT: ${{ secrets.PRIVATE_REPO_PAT }}
        run: |
          git clone https://x-access-token:${PRIVATE_REPO_PAT}@github.com/Protocol-Roleplay/Status.git private-config

      - name: Run health checks and generate logs
        run: bash ./scripts/health-check.sh

      - name: Commit and push logs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add status/
          git commit -m "[Automated] Update Health Check Logs" || echo "No changes to commit"
          git push
